### ISSUE TITLE
Can't tap into the `adend` event

### ISSUE THREAD

**Issue by mayeaux** [mysuf/videojs-ima-player#13]
How can I access the `adend` event? Sometimes the player doesn't start and I want to try to run a `player.play()` after the ad if I can.

```
player.ima({adTagUrl: macroUrl});

player.ima.on('adend', function(event){
    console.log('AD ENDED')
})
```
Complains that `player.ima.on` is not a function.

Thanks, awesome module!

**Comment by mysuf** [comment]
Hello,

I guess that what `google.ima.AdEvent.Type.COMPLETE` what you want. If `player.ima.on` is not a function then you probably call it at wrong place or you have adblock enabled. I recommend you to look at [examples](https://github.com/mysuf/videojs-ima-player/tree/master/examples). Every example has demo page (right column at repository main page).
