### ISSUE TITLE
How to bind a function to a error event?

### ISSUE THREAD

**Issue by thrieu** [mysuf/videojs-ima-player#3]
Neither of the following 2 ways work.
```javascript
player.ima.on("adserror", function(e) {
    console.log(e);
}
```
 
```javascript
player.on("adserror", function(e) {
    console.log(e);
}
```

How could I achieve that?

Thx!!!

**Comment by mysuf** [comment]
Hi,

adserror is internal event. Use google.ima.AdErrorEvent.Type.AD_ERROR instead (look at README, section events)

**Comment by thrieu** [comment]
Thanks for quick reply! it work.
