### ISSUE TITLE
Does the player support the playing of skippable ads on smart TV?

### ISSUE THREAD

**Issue by huangdaman** [mysuf/videojs-ima-player#6]
I am developing The advertising function of smart TV on tizen simulator.Other types of ads work fine, but skipping ads are reported with an error of 1005.
    I try to set up playsinline properties and setDisableCustomPlaybackForIOS10Plus to true, Unfortunately the same error was reported.

**Comment by mysuf** [comment]
Did you try setting up playsinline in videojs's options? like `videojs('el', {playsinline: true})`? Dynamically added attributes does not apply to videojs player element.

**Comment by huangdaman** [comment]
Thank you very much for your reply!  I set the playsinline on the video tag.

**Comment by huangdaman** [comment]
HI,
  I set the playsinline on the video tag but the same error was reported. Is this method only suitable for mobile, not for smart TV?

**Comment by mysuf** [comment]
Hmm.. This behaviour is related to IMA SDK so I'm not sure that I can help.. You should look at his forum. Its possible that somebody already solved similar issue.

**Comment by huangdaman** [comment]
Thank you anyway
