### ISSUE TITLE
Does this SDK support playing multiple ads

### ISSUE THREAD

**Issue by huangdaman** [mysuf/videojs-ima-player#7]
Hi
    How to set up to play multiple ads, adTagUrl settings seem to only expect strings
    Try to aggregate multiple ads into VMAP, then pass in adsResponse, but not work
    If I reset the ad address in the ima complete event, I receive an error player.ima is not a function

**Comment by mysuf** [comment]
It is done same way as official plugin. [There is number of examples](https://mysuf.github.io/videojs-ima-player/)

**Comment by huangdaman** [comment]
Hi mysuf
  I tried to play the second ad by using the player.ima.changeAdTag method in the ad complete event in the [official simple examples](https://github.com/googleads/videojs-ima/tree/master/examples) and then calling player.ima.requestAds(). But in the current SDK using the same method but received an error player.ima.changeAdTag is not a function, can you help me see what is the reason?

**Comment by huangdaman** [comment]
[simple.zip](https://github.com/mysuf/videojs-ima-player/files/3226333/simple.zip)
This is the demo I wrote.

**Comment by mysuf** [comment]
Hi, if you want multiple ads, then vmap is way to go. So you should provide either vmap file in adTagUrl or compose vmap string and pass into adsResponse. I dont think that you can simply change VAST during content playback.
